version: '2'
services:
  irc:
    build: irc/.
    tty: true
    links:
    - zk

  display:
    build: display/.
    tty: true
    links:
    - zk

  zk:
    image: wurstmeister/zookeeper
    ports: 
    - 2181:2181

