version: '2'
services:
  irc:
    build: irc/.
    tty: true
    links:
    - zookeeper:zk

  lcd:
    build: display/.
    tty: true
    links:
    - zookeeper:zk

  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
    - 2181:2181
